export interface Household {
  id              : string,
  id_health_zone  : number,
  health_zone     : string,
  id_health_center: number,
  health_center   : number,
  id_city         : number,
  city            : string,
  id_commune      : number,
  commune         : string,
  id_district     : number,
  district        : string,
  id_avenue       : number,
  avenue          : string,
  id_user         : number,
  user            : string,
  number          : string,
  latitude        : string,
  longitude       : string,
  state           : string,
  sync            : number,
  created_at      : string,
  updated_at      : string,
}
