export interface Member {
  id               : number,
  id_household     : string,
  id_relationship  : string,
  relationship     : string,
  id_marital_status: string,
  marital_status   : string,
  id_schooling     : string,
  schooling        : string,
  id_religion      : string,
  religion         : string,
  id_nationality   : number,
  nationality      : string,
  fullname         : string,
  gender           : string,
  dob              : string,
  pob              : string,
  profession       : string,
  phone            : string,
  mutual           : number,
  alergy           : string,
  registration_date: string,
  release_date     : string,
  observation      : string,
  sync             : number,
  created_at       : string,
  updated_at       : string
}
