export interface SocialEconomicLevel {
  id                           : number,
  id_household                 : string,
  profession_head_of_household : string,
  other_profession             : string,
  usual_source_of_income       : string,
  proprio_location             : string,
  rent_amount                  : number,
  number_habitation            : number,
  number_of_member             : number,
  bedroom                      : number,
  other_factor                 : string,
  capacity_cost                : string,
  payment_type                 : string,
  other_info                   : string,
  sync                         : number,
  created_at                   : string,
  updated_at                   : string,
}
